from enum import Enum


class TelemetryState(str, Enum):
    BOOTING = "BOOTING"
    WAITING_NETWORK = "WAITING_NETWORK"
    NORMAL = "NORMAL"
    DEGRADED_SENSOR = "DEGRADED_SENSOR"
    UPLOADING = "UPLOADING"
    THERMAL_CRITICAL = "THERMAL_CRITICAL"
    SHUTTING_DOWN = "SHUTTING_DOWN"
    ERROR = "ERROR"
